# =============================================================================
# Hardware Configuration - Desktop (nixos host)
# =============================================================================
# This file was generated by 'nixos-generate-config' and is specific to the
# desktop/nixos host hardware. It is imported only by modules/hardware/desktop.nix
# and should NOT be imported by server or WSL roles.
#
# For other hosts, generate a separate hardware configuration using:
#   nixos-generate-config --show-hardware-config
#
# Note: Do not add ephemeral mounts (like k8s pod volumes) to this file.
# =============================================================================
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "ahci"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b6206822-bce2-43bb-a0d7-8e0965fb535b";
    fsType = "btrfs";
    options = [ "subvol=@root" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/b6206822-bce2-43bb-a0d7-8e0965fb535b";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/b6206822-bce2-43bb-a0d7-8e0965fb535b";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/var/lib/rancher" = {
    device = "/dev/disk/by-uuid/b6206822-bce2-43bb-a0d7-8e0965fb535b";
    fsType = "btrfs";
    options = [ "subvol=@k3s" ];
  };

  fileSystems."/home/liberis/sharedData" = {
    device = "/dev/disk/by-uuid/061470EB1470DF5D";
    fsType = "ntfs";
    options = [
      "uid=1000"
      "gid=100"
      "dmask=022"
      "fmask=133"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0AC6-2BA0";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
