# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ata_generic" "ehci_pci" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/819ffdc1-8d70-4ee4-9dfa-b7056171caa5";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/819ffdc1-8d70-4ee4-9dfa-b7056171caa5";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/819ffdc1-8d70-4ee4-9dfa-b7056171caa5";
      fsType = "btrfs";
      options = [ "subvol=@var-log" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/819ffdc1-8d70-4ee4-9dfa-b7056171caa5";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/819ffdc1-8d70-4ee4-9dfa-b7056171caa5";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/lib/rancher" =
    { device = "/dev/disk/by-uuid/819ffdc1-8d70-4ee4-9dfa-b7056171caa5";
      fsType = "btrfs";
      options = [ "subvol=@rancher" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/466B-714D";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # fileSystems."/tank" =
  #   { device = "tank";
  #     fsType = "zfs";
  #   };
  #
  #
  # fileSystems."/tank/k8s/volumes" =
  #   { device = "tank/k8s/volumes";
  #     fsType = "zfs";
  #   };
  #
  # fileSystems."/tank/k8s/snapshots" =
  #   { device = "tank/k8s/snapshots";
  #     fsType = "zfs";
  #   };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
