# =============================================================================
# Hardware Configuration - jarvis (AMD Ryzen 9900X Desktop)
# =============================================================================
# IMPORTANT: This is a placeholder file for dual-boot setup.
#
# During Windows + NixOS dual-boot installation, this file will be REPLACED
# by the actual hardware-configuration.nix generated by nixos-generate-config.
#
# Installation process:
# 1. Install Windows 11 first (creates EFI partition)
# 2. Shrink Windows partition to make room for NixOS
# 3. Boot NixOS installer and manually partition remaining space
# 4. Run: nixos-generate-config --root /mnt
# 5. This file gets replaced with actual hardware config
# 6. Run: nixos-install --flake .#jarvis
#
# See: JARVIS_INSTALLATION_GUIDE.md for complete instructions
# =============================================================================
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # These will be populated during installation based on actual hardware
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Filesystem configuration (will be replaced during installation)
  # Expected layout after installation:
  #   /dev/nvme0n1p1 → /boot (EFI, shared with Windows)
  #   /dev/nvme0n1p4 → swap (32GB)
  #   /dev/nvme0n1p5 → / (BTRFS with subvolumes)

  # ===========================================================================
  # OS Drive - 1TB NVMe (nvme0n1)
  # ===========================================================================
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [ "subvol=@root" "compress=zstd" "noatime" "discard=async" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/EFI";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [ "subvol=@home" "compress=zstd" "noatime" "discard=async" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [ "subvol=@nix" "noatime" "nodatacow" "discard=async" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [ "subvol=@var-log" "compress=zstd" "noatime" "discard=async" ];
  };

  fileSystems."/var/lib/rancher" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [ "subvol=@rancher" "noatime" "nodatacow" "discard=async" ];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [ "subvol=@snapshots" "compress=zstd" "noatime" "discard=async" ];
  };

  # ===========================================================================
  # Data Drive - 2TB NVMe (nvme1n1)
  # ===========================================================================
  fileSystems."/mnt/k3s-storage" = {
    device = "/dev/disk/by-label/data";
    fsType = "btrfs";
    options = [ "subvol=@k3s-storage" "noatime" "compress=zstd" "discard=async" ];
  };

  fileSystems."/mnt/games" = {
    device = "/dev/disk/by-label/data";
    fsType = "btrfs";
    options = [ "subvol=@games" "noatime" "nodatacow" "discard=async" ];
  };

  fileSystems."/mnt/media" = {
    device = "/dev/disk/by-label/data";
    fsType = "btrfs";
    options = [ "subvol=@media" "noatime" "compress=zstd" "discard=async" ];
  };

  fileSystems."/mnt/downloads" = {
    device = "/dev/disk/by-label/data";
    fsType = "btrfs";
    options = [ "subvol=@downloads" "noatime" "compress=zstd" "discard=async" ];
  };

  # Swap device (will be configured during installation)
  swapDevices = [
    { device = "/dev/disk/by-label/swap"; }
  ];

  # Networking
  networking.useDHCP = lib.mkDefault true;

  # CPU microcode
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
